In [28]:
import pandas as pd
import numpy as np
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Embedding, Flatten, Dense

In [7]:
data = pd.read_csv('path to the train dataset', sep =';')

In [8]:
data.columns = ["Text", "Emotions"]
print(data.head())

                                                Text Emotions
0  i can go from feeling so hopeless to so damned...  sadness
1   im grabbing a minute to post i feel greedy wrong    anger
2  i am ever feeling nostalgic about the fireplac...     love
3                               i am feeling grouchy    anger
4  ive been feeling a little burdened lately wasn...  sadness


In [9]:
texts = data["Text"].tolist()
labels = data["Emotions"].tolist()

tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)


seq = tokenizer.texts_to_sequences(texts)
max_length = max([len(seq) for seq in seq])
padded_sequences = pad_sequences(seq, maxlen=max_length)

In [10]:
seq = tokenizer.texts_to_sequences(texts)

In [11]:
padded_sequences

array([[   0,    0,    0, ...,    3,   21, 1254],
       [   0,    0,    0, ...,    2,  494,  437],
       [   0,    0,    0, ...,   29,    5, 3496],
       ...,
       [   0,    0,    0, ...,    3,  101, 1331],
       [   0,    0,    0, ...,  339,    8,   42],
       [   0,    0,    0, ...,   25, 3585,   12]], dtype=int32)

In [12]:
label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(labels)

In [13]:
one_hot_labels = keras.utils.to_categorical(labels)

In [14]:
one_hot_labels

array([[0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [15]:
xtrain, xtest, ytrain, ytest = train_test_split(padded_sequences,
                                                one_hot_labels,
                                                test_size=0.2)

In [16]:
one_hot_labels[0]

array([0., 0., 0., 0., 1., 0.])

In [17]:
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1,
                    output_dim=128, input_length=max_length))
model.add(Flatten())
model.add(Dense(units=128, activation="relu"))
model.add(Dense(units=len(one_hot_labels[0]), activation="softmax"))

model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])
model.fit(xtrain, ytrain, epochs=10, batch_size=32, validation_data=(xtest, ytest))

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


400/400 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.3942 - loss: 1.5193 - val_accuracy: 0.7344 - val_loss: 0.8132
Epoch 2/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.8722 - loss: 0.4198 - val_accuracy: 0.8300 - val_loss: 0.5262
Epoch 3/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9830 - loss: 0.0633 - val_accuracy: 0.8356 - val_loss: 0.5846
Epoch 4/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 18s 45ms/step - accuracy: 0.9947 - loss: 0.0245 - val_accuracy: 0.8288 - val_loss: 0.6139
Epoch 5/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - accuracy: 0.9972 - loss: 0.0140 - val_accuracy: 0.8278 - val_loss: 0.6747
Epoch 6/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9976 - loss: 0.0127 - val_accuracy: 0.8263 - val_loss: 0.6792
Epoch 7/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 14s 35ms/step - accuracy: 0.9982 - loss: 0.0081 - val_accuracy: 0.8263 - val_loss: 0.6616
Epoch 8/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9980 - loss: 0.0095 - val_accurac

In [27]:

usr_inp = "Hello everyone, today is a sunny day.I'm very happy for to my life"


input_sequence = tokenizer.texts_to_sequences([usr_inp])
padded_input_sequence = pad_sequences(input_sequence, maxlen=max_length)


prediction = model.predict(padded_input_sequence)
predicted_label = label_encoder.inverse_transform([np.argmax(prediction[0])])


print("Predicted label:", predicted_label[0])


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
Predicted label: joy
